# docs/_config.yml

title: "CancerCellModel"
description: "An end-to-end breast cancer classification pipeline using Python and scikit-learn."
url: "https://bitpest.github.io"
baseurl: "https://github.com/bitpest/Breast-Cancer-Model"

# Theme and Plugins
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Markdown Processing
markdown: kramdown
highlighter: rouge

# URL Structure
permalink: /:title/

# Navigation Structure
navigation:
  - title: "Home"
    url: "/#{site.baseurl}/"
  - title: "Demo"
    url: "/#{site.baseurl}/demo/"
  - title: "Documentation"
    url: "/#{site.baseurl}/documentation/"
  - title: "Analysis & Visualizations"
    url: "/#{site.baseurl}/analysis/"
  - title: "Contact"
    url: "/#{site.baseurl}/contact/"

# SEO
seo:
  type: "website"
  name: "CancerCellModel"
  description: "An interactive and documented example of breast cancer classification using scikit-learn, Random Forest, and advanced visual analytics."


# Files to Exclude
exclude:
  - LICENSE
  - CancerCellModel.py
  - README.md
  - .gitignore

# Default Layouts and Values
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true


